function [fitresult, gof] = createFits(X, IM, RE)
%CREATEFITS(X,IM,RE)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Output: IM
%  Data for 'untitled fit 2' fit:
%      X Input : X
%      Y Output: RE
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-May-2022 23:09:28

%Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, IM );

% Set up fittype and options.
ft = fittype( 'b0+b1*sin(w*x)+b2*sin(2*w*x)+b3*sin(3*w*x)+b4*sin(4*w*x)+b5*sin(5*w*x)+b6*sin(6*w*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf 40000000];
opts.StartPoint = [0.505957051665142 0.699076722656686 0.890903252535798 0.959291425205444 0.547215529963803 0.196595250431208 0.251083857976031 0.1386];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf 400000000];

% % Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( X, RE );

% Set up fittype and options.
ft = fittype( 'a0+a1*cos(w*x)+a2*cos(2*w*x)+a3*cos(3*w*x)+a4*cos(4*w*x)+a5*cos(5*w*x)+a6*cos(6*w*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf -Inf 40000000];
opts.StartPoint = [0.149294005559057 0.257508254123736 0.840717255983663 0.254282178971531 0.814284826068816 0.929263623187228 0.349983765984809 0.2435];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf 400000000];

% % Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );


a=[fitresult{2}.a0, fitresult{2}.a1, fitresult{2}.a2, fitresult{2}.a3, fitresult{2}.a4, fitresult{2}.a5, fitresult{2}.a6]
b=[fitresult{1}.b0, fitresult{1}.b1, fitresult{1}.b2, fitresult{1}.b3, fitresult{1}.b4, fitresult{1}.b5, fitresult{1}.b6]
